# Generated by Django 4.0.5 on 2022-06-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_remove_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
