# Generated by Django 4.0.5 on 2022-06-07 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0012_follow_post_stream_tag_delete_image_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
