# Generated by Django 4.0.5 on 2022-06-08 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0018_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
